services:
  service-users:
    build: ./users-service
    container_name: service-users
    ports:
      - "3001:3000"
    restart: always
    environment:
      DB_HOST: users-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: usersdb
      DB_PORT: 5432
      SCHEDULING_API: http://service-scheduling:3000
      REDIS_HOST: redis-users
      REDIS_PORT: 6379
    env_file:
      - users-service/.env
    volumes:
      - ./users-service/uploads:/usr/src/app/uploads
    depends_on:
      users-db:
        condition: service_healthy
    networks:
      - agendafacil_network

  users-db:
    image: postgres:15
    container_name: users-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usersdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - users_data:/var/lib/postgresql/data
    networks:
      - agendafacil_network

  redis-users:
    image: redis:7
    container_name: redis-users
    restart: always
    ports:
      - "6379:6379"
    networks:
      - agendafacil_network

  nginx-users:
    image: nginx:alpine
    container_name: nginx-users
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./users-service/uploads:/usr/share/nginx/uploads:ro
    ports:
      - "8080:8080"
    depends_on:
      - service-users
    networks:
      - agendafacil_network

volumes:
  users_data:

networks:
  agendafacil_network:
    external: true
